title: Ruggeri Dev Blog
email: truggeri@gmail.com
description: >- 
  A small developer blog
baseurl: ""
url: "https://www.truggeri.com"
github_username:  truggeri

navigation:
  - name: Home
    link: "/"
  - name: About Me
    link: "/about"
  - name: Resume
    link: "/resume"

theme: jekyll-theme-architect
plugins:
  - jekyll-feed

collections:
  tags:
    output: true
    permalink: tags/:path/
